// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hrukgkkfkfvrhfkhfslk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhydWtna2tma2Z2cmhma2hmc2xrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5NTgxMzgsImV4cCI6MjA3NDUzNDEzOH0.ZWNRly_ie8v_wKsREK25HKQ8b22FyAQXTOHFi4FyWks";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});